extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/*/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python3 ./unit_passes/dead_code_elimination.py",
    "bril2json",
    "brili -p {args}",
]

[runs.rod]
pipeline = [
    "bril2json",
    "python3 ./unit_passes/rename_old_defs.py",
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "python3 lvn_opt.py",
    "bril2json",
    "brili -p {args}",
]

