[envs.make]
command = "make all"

[envs.dump_llvm]
command = "$LLVM/bin/clang -emit-llvm -S -o build/{base}.llvm {filename}"
output.llvm = "../build/{base}.llvm"

[envs.dump_baii_llvm]
command = "$LLVM/bin/clang -f-fpass-plugin=build/BoolAlgInInt/BoolAlgInInt.so -emit-llvm -S -o - {filename}"
output.baai.llvm = "-"
